### ISSUE TITLE
suggestions for the next device-type

### ISSUE THREAD

**Issue by SCIEN-00** [microsoft/ArduinoHidForWindows#4]
I would like to have Arduino due as supported device

**Comment by DIGITDUDE** [comment]
how is the support for mbed_giga structure. because i keep getting various errors

error: 'Microsoft_HidConsumerControl' does not name a type
 Microsoft_HidConsumerControl consumerControl = Microsoft_HidConsumerControl();

error: 'consumerControl' was not declared in this scope
             consumerControl.incrementVolume();

and more like these over all the separte classes. does it have to do with trying to run on mbed_giga structure or is there something else going on.

**Comment by matwilli** [comment]
I'm not familiar with the mbed_giga Arduino platform.  This library has only been written-for/validated on Arduino SAMD21 devices (e.g. Arduino Zero); other platforms may not support the required USB functionality.
